http:
  routers:
    arcturus_ws:
      entryPoints:
        - websecure
      rule: "Host(`chasethe.duckdns.org`) && PathPrefix(`/_ws`)"
      service: "arcturus_ws"
      middlewares:
        - arcturus-strip-ws-prefix
      tls:
        certResolver: myresolver
      priority: 10

  middlewares:
    arcturus-strip-ws-prefix:
      stripPrefix:
        prefixes:
          - "/_ws"

  services:
    arcturus_ws:
      loadBalancer:
        servers:
          - url: "http://arcturus:2096"
        passHostHeader: true
    
    arcturus_game:
      loadBalancer:
        servers:
          - url: "http://arcturus:3000"
        passHostHeader: true
    
    arcturus_rcon:
      loadBalancer:
        servers:
          - url: "http://arcturus:3001"
        passHostHeader: true