http:
  routers:
    nitro_client:
      entryPoints:
        - websecure
      rule: "Host(`chasethe.duckdns.org`)
      service: "nitro_client"
      tls:
        certResolver: myresolver
      priority: 1


  services:
    nitro_client:
      loadBalancer:
        servers:
          - url: "http://nitro:80"
        passHostHeader: true